name: brick_balls_game
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  flame: ^1.12.0
  flame_audio: ^2.1.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  provider: ^6.1.1
  vibration: ^1.8.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
